version: '2'
services:
  prometheus:
    image: 'prom/prometheus'
    restart: unless-stopped
    ports:
      - '9090:9090'

  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

